import turtle

MyTurtle = turtle.Turtle()

def loop(c='black'):
    MyTurtle.color(c)
    MyTurtle.penup()
    MyTurtle.backward(250)
    MyTurtle.pendown()
    MyTurtle.forward(100)
    MyTurtle.left(65)
    MyTurtle.forward(55)
    MyTurtle.right(65)
    MyTurtle.forward(200)
    MyTurtle.right(60)
    MyTurtle.forward(60)
    MyTurtle.left(60)
    MyTurtle.forward(90)
    MyTurtle.right(55)
    MyTurtle.forward(80)
    MyTurtle.right(125)
    MyTurtle.penup()
    MyTurtle.forward(100)
    MyTurtle.pendown()
    MyTurtle.circle(90)
    MyTurtle.penup()
    MyTurtle.left(90)
    MyTurtle.forward(90)
    MyTurtle.right(90)
    MyTurtle.forward(90)
    MyTurtle.pendown()
    MyTurtle.forward(150)
    MyTurtle.right(90)

    MyTurtle.circle(90)
    MyTurtle.right(90)
    MyTurtle.penup()
    MyTurtle.backward(180)
    MyTurtle.pendown()
    MyTurtle.backward(15)
    MyTurtle.left(90)
    MyTurtle.forward(158)
    MyTurtle.left(90)
    MyTurtle.backward(100)

    MyTurtle.penup()
    MyTurtle.backward(434)
    MyTurtle.left(90)
    MyTurtle.forward(70)
    MyTurtle.pendown()
    MyTurtle.right(60)
    MyTurtle.forward(45)


loop('green')

